name: Azure multi-deploy
description: Creates instances, builds, deploys web & function apps to azure. Supports staging deployments in PRs
author: DHI-GRAS
inputs:
  azureCredentials:
    description: Azure credentials in JSON format
    required: true
runs:
  using: composite
  steps:
    - name: Install & build
      run: yarn && yarn build && yarn runmain
      shell: bash
