name: PR
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  deploy:
    name: deploy
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install
        run: yarn && yarn build ; yarn runmain
